In [1]:
import pandas as pd
import numpy as np

In [3]:
distMat = pd.read_csv("../dist_matrix120.csv")

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,708,709,710,711,712,713,714,715,716,717
0,0,0.0,0.2218,0.33866,0.43871,0.57345,0.76186,0.62142,0.68699,0.62765,...,1.46147,0.89891,0.64483,0.62053,0.99531,0.87780,1.27322,1.40587,1.18563,0.99568
1,1,0.0,0.0000,0.17411,0.25216,0.49993,0.44423,0.40295,0.52888,0.64097,...,1.07660,0.59883,0.39697,0.44208,0.76347,0.91668,1.09351,1.22615,1.00592,0.81596
2,2,0.0,0.0000,0.00000,0.12571,0.23185,0.57596,0.45320,0.50834,0.41393,...,1.25303,0.63609,0.32810,0.25115,0.60076,0.35522,1.02535,1.09512,0.80622,0.67149
3,3,0.0,0.0000,0.00000,0.00000,0.17623,0.44262,0.49030,0.47048,0.41759,...,0.94186,0.64636,0.33315,0.31011,0.48963,0.31138,0.79370,0.80485,0.58690,0.55981
4,4,0.0,0.0000,0.00000,0.00000,0.00000,0.31198,0.36394,0.36966,0.22405,...,0.80342,0.55765,0.32987,0.32893,0.34083,0.26545,0.56264,0.51158,0.38780,0.40303